resources:
  - name: slash_dbp_repo
    type: GitRepo
    configuration:
      gitProvider: slash_github_pipelines          # <-- replace with your integration
      path: slash-l/JFrogPipelines                 # <-- replace with your repository name
      branches:
        include: master

  - name: slash_dbp_image
    type: Image
    configuration:
      registry: art                                # <-- replace with your artifactory integration
      sourceRepository: docker_local               # <-- required if registry is Artifactory
      imageName: kaloula.jfrog-pipelines.com/docker-local/dbp  # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: slash_dbp_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: dbp_build
      buildNumber: 1

  - name: slash_dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: dbp_build
      buildNumber: 1
      

pipelines:
  - name: slash_pipeline_dbp
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: kaloula.jfrog-pipelines.com/docker-local/dbp  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: slash_dbp_repo
          integrations:
            - name: art                            # <-- replace with your artifactory integration

      - name: slash_docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker-local
          integrations:
            - name: art                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: slash_dbp_image

      - name: slash_publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: slash_dbp_build_info

      - name: slash_promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: demo-pipelines
          integrations:
            - name: art
          inputResources:
            - name: slash_dbp_build_info
          outputResources:
            - name: slash_dbp_promoted_build_info

